### ISSUE TITLE
Fails if answers' text contains special characters

### ISSUE THREAD

**Issue by sibiryoff** [tolstoyevsky/hubot-vote-or-die#2]
Example: 
`!poll question 1, a1, a2, #general , @newman`

**Comment by TheSergeX** [comment]
Only if answer text starts with `#`.

**Comment by eugulixes** [comment]
Now the problem is not relevant
![image](https://user-images.githubusercontent.com/5358223/50163775-3a99a600-02f2-11e9-869f-b73f9e8597d8.png)

Rocket.Chat: 0.70.4
Hubot: 3.1.1
hubot-rocketchat: 2.0.0-development
